---
title: "DS 202 Project Proposal"
author: John Banta (Project Coordinator), Kelsey Mclnturff, Luping Wang, and Brenna
  Walters
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Important Links

[Data](https://www-fars.nhtsa.dot.gov/Trends/TrendsGeneral.aspx)

[Github Repository](https://github.com/jdbanta/DS202_Final_Project)

## Sections {.tabset}

### Dataset Overview

The United States National Highway Traffic Safety Aministration website reports statistics on fatal crashes as part of the Fatality Analysis Reporting System. This dataset is broken into many different tables to emphasize different variables. This dataset is updated yearly to continue informing the US public. Currently, data from years 1994 to 2017 is available. Furthermore, the data can be downloaded in a variety of ways for easy analysis.

***

**The data tables available are as follows:**
 
 
Summary

* General

Trends

* General
* Occupants
* Large Truck Related
* Nonmotorists
* Alcohol
* Restraints

Crashes

* Time
* Location
* Circumstances
* Alcohol
  
Vehicles

* All Vehicles
* Location
* Passenger Cars
* Light Trucks
* Large Trucks
* Motorcycles
* Buses
  
People

* All Victims
* Drivers
* Occupants
* Restraints
* Motorcyclists
* School Bus Related
* Pedestrians
* Pedalcyclists
  
States

* Crashes and All Victims
* Occupants
* Pedestrians
* Alcohol
* Fatalities and Fatality Rates
* Laws


### Background

Nation-wide motor vehicle accidents are a topic of safety that concern both the general public and lawmakers. Statistics through the National Highway Traffic Safety Administration provide the means for insight into what factors influence collisions. These insights could provide awareness for drivers on what factors to be wary of while driving, such as number of passengers, weather conditions, location, time of day, and other variables that the data provide. Communicating the relationships the data reveal can allow drivers to be safer in or avoid conditions that are more prone to accidents. For lawmakers, the same insights could influence traffic laws which increase safety on the road. In addition to influencing traffic laws, the data could provide insight into why current traffic laws are currently in place, such as legal limits for alcohol. The collision data is expansive and lends itself to many angles for analysis. As data exploration and data cleaning progress, we will be able to narrow the scope of analysis and determine the effect a handful of factors have on collision rates.

### Plan for Analysis

Our goal in analyzing the data is to learn about which factors contribute the most to the number of fatal traffic accidents in the US. Some questions we are interested in answering with the data are:

* During what time period has the highest accident rate?

* What is the relationship between the number of victims and the driver blood alcohol concentration?

* What type of vehicle has the highest rate of collision? How is the vehicle type related to the number of victims?

* Who are the people(race, gender, age) who die in these accidents?


Before conducting the analysis, we are going to clean the dataset. We will drop the NAs and irrelivant columns, eliminate duplicates, and transform the data as needed. Since the data is broken into several different tables, we will need to join several of them together using year as a key.

To visualize the data, we will use mainly tables and ggplot. We will use several different types of plots (histograms, barplots, scatterplot matrix, correlation matrix, ect.) to see how variables are distributed and how thay relate to the number of fatal accidents. By visualizing the data this way, we hope to see relationships that help us answer the questions listed above.


